### ISSUE TITLE
Convert trips to CO2

### ISSUE THREAD

**Issue by teubert** [teubert/impact-estimator#11]

**Comment by teubert** [comment]
I'm working on this now. I'm going to create the logic to do this. Initially it will be built into the app.

**Comment by xuangreradyi** [comment]
Hi All
What I got is something like this
Actually the GPS API has the speed, so we don't have to calculate.





2018-03-04 19:39 GMT-08:00 Christopher Teubert <notifications@github.com>:

**Comment by teubert** [comment]
@xuangreradyi: The speed helps us infer the transport mode for trips (one segment of travel under one mode of transport), but this work was to convert from the trips to kg of CO2. 

Do you already have something that does that?

**Comment by xuangreradyi** [comment]
If you don't want to let user type in the transport mode manually, we can
just do the simple calculation to infer the mode by speed.
Once we confirm the transport mode. The CO2 calculation should be clear.
For example. As far I researched for a sedan.


   - CO2 Emissions from a gallon of gasoline: 8,887 grams CO2/ gallon
   - CO2 Emissions from a gallon of diesel: 10,180 grams CO2/ gallon

Then we can just multiply by the average MPG  and divide by speed.
For example Honda Civic MPG is 40. and the speed is also 40 MPH.
Then the CO2 emission should be 8887 g x 40 / 40 = 8887g. (per hour)
The output should be the totall CO2 emission that we are looking for.
Am I correct ?



2018-03-04 19:47 GMT-08:00 Christopher Teubert <notifications@github.com>:

**Comment by teubert** [comment]
Yep, that's right. That's what I implemented to convert from trips to impact. 

You can see the equations here:
   - https://github.com/teubert/impact-estimator/blob/master/Chris_Database/app/src/main/java/edu/scu/databaseexample/FootprintEstimate.java

The equations also include other forms of CO2 (food, etc.)

I wish you had marked the issue as yours so we didn't overlap. I had assigned the issue to me when we last met. I thought you were working on getting GPS points in a service and converting them to trips (the issues assigned to you here on Github).

Let's plan on getting together on Tuesday so we can merge everything that we have together.

**Comment by xuangreradyi** [comment]
I see   Very nice job


2018-03-04 20:10 GMT-08:00 Christopher Teubert <notifications@github.com>:
