### ISSUE TITLE
Setup Cloud-Based Database 

### ISSUE THREAD

**Issue by teubert** [teubert/impact-estimator#16]

**Comment by teubert** [comment]
Here is what I was thinking for the JSON Structure for the firebase database. Note the things in caps are replaced with the data for that thing (TIMESTAMP replaced with Linux-time, or another timestamp). What do you guys think @xuangreradyi @Xiacsummer @qgaoi 

{
    // Information about registered users
    "users": {
          "[EMAIL]": {
                   "car_type": "CAR-TYPE-HERE",
                   "user_since": TIMESTAMP,
                   "last_signin": TIMESTAMP
            }, ...
      },
      
     // Unfiltered GPS Data
      "unfiltered_gps_data": {
             "[EMAIL]": {
                  "[TIMESTAMP]": {
                      "lat": ###,
                      "lon": ###
                  }, ...
             }, ...
        },

       // Trips
       "trips": {
           "[EMAIL]":{
               "[DAY]": {
                    "[TRIP_ID]": {
                           "transport_mode": [MODE_ID]
                           "start": {
                                "timestamp": [TIMESTAMP],
                                "lat": [LAT],
                                "lon": [LON]
                           },
                           "end": {
                                "timestamp": [TIMESTAMP],
                                "lat": [LAT],
                                "lon": [LON]
                           }
                    // End Trip
                    }, ...
              // End Day
              },...
           // End User
           },...
      // End trips
      },...
                                
       // Impact Estimates
      "Impact_Estimates": {
           "[EMAIL]": {
                 "summary": {
                      // Put in its own struct so getting the summary for an email will not have to download every day's data
                      "TOTAL": ###,
                      "NDAYS": ###
                  },
                 "Daily": {
                       "[DAYNAME]": {
                              // Put in a struct for extendability
                             "Total": ### 
                       }, ...
                  }
            // End for individual user
            }, ...
       // End of impact estimate
       }
}

**Comment by teubert** [comment]
I have a Firebase real-time database setup. I'm working on creating a Java class to handle writing/reading from the database. I'll share it with you once it's ready so you can start using it. 

Let me know ASAP if you have any input on the above JSON.

**Comment by qgaoi** [comment]
Taking out the forbidden characters is fine. In addition, I think we also need to store users' passwords in the registration part.

**Comment by Xiacsummer** [comment]
I'm not familiar with JSON structure yet. 

"users": {
"[USER_NAME]": {
"email": "[EMAIL]
"car_type": "CAR-TYPE-HERE",
"user_since": TIMESTAMP,
"last_signin": TIMESTAMP
}, ...
}

Does this mean the users are differentiated by usernames? Is so I suggest use email. Since the signup will require email. So every user has their unique email address instead of unique username.

**Comment by teubert** [comment]
@Xiacsummer I was going to use the emails, but Firebase doesn't allow me to use emails as a key, so I have to use something else. In this case I'm defining username as the email address with @ and . replaced with _. That way we are still using the email address as the unique username

@qgaoi Good point, I'll add that in

**Comment by teubert** [comment]
Progress report:

I just checked in the first version of the DatabaseHelper class here:
https://github.com/teubert/impact-estimator/blob/master/Chris_Database/app/src/main/java/edu/scu/databaseexample/ImpactDatabaseHelper.java

Functions done:
- AddNewUser()
- AddNewGPSDatapoint()

Functions remaining:
- UpdateLastLogin()
- AddTrip(Trip )
- AddImpactEstimate(User id, Impact_Estimate)
- GetUser(User id)
- GetGPS(User id)
- GetTrips(User id)
- GetTrips(User id, Day day)
- GetImpactEstimate(User id)
- GetImpactEstimate(User id, Day day)

**Comment by teubert** [comment]
Did some more work today, current status:

Functions done & tested:
- AddNewUser()
- AddNewGPSDatapoint()

Functions done but not tested:
- UpdateUser()
- addNewGPSDataPoint()
- updateLastLogin()

Functions started but not completed:
- removeGPSPoints()
- addTrip()
- removeTrip()
- addToDayEstimate()

Functions remaining:
- GetUser(User id)
- GetGPS(User id)
- GetTrips(User id)
- GetTrips(User id, Day day)
- GetImpactEstimate(User id)
- GetImpactEstimate(User id, Day day)

**Comment by teubert** [comment]
Did some more work today, current status:

Functions done & tested:

AddNewUser()
AddNewGPSDatapoint()
Functions done but not tested:
- UpdateUser()
- addNewGPSDataPoint()
- updateLastLogin()

Functions started but not completed:
- removeGPSPoints()
- addTrip()
- removeTrip()
- addToDayEstimate()
- GetUser(User id)
- GetGPS(User id)
- GetTrips(User id, Day day)
- GetImpactEstimate(User id)
- GetImpactEstimate(User id, Day day)

**Comment by Xiacsummer** [comment]
Chris,

We can use Firebase Generated ID. It is Unique to every registered user.  Sample code at below.
private FirebaseUser user;
user = FirebaseAuth.getInstance().getCurrentUser();
final String Id = user.getUid();

**Comment by teubert** [comment]
Great find! That would work as long as we're using FirebaseAuth for authentication. Are you planning on using that for the login page?

**Comment by Xiacsummer** [comment]
Yes, I'm using FirebaseAuth for login and signup.

**Comment by teubert** [comment]
Great! I'll use that then. 

I cannot use it without FirebaseAuth, so let me know when you have the login logic completed and I will integrate it into my project. 

In the meantime, I'll continue developing the rest of the database helper.

**Comment by Xiacsummer** [comment]
I have done the login and sign up processes. If you get to class early today I can show u. Let me know your schedule. Text me at 307-223-6401 if I do not response u here.

**Comment by teubert** [comment]
Great, can you check it into the repo?

Yes, I'm available anytime after 3. Where do you want to meet?

**Comment by Xiacsummer** [comment]
I will be in library 104 from 2pm. Still have not got github work for me. Can you help out in the afternoon?

**Comment by teubert** [comment]
Sure! I'll text you when I'm nearby.
