### ISSUE TITLE
GPS module 

### ISSUE THREAD

**Issue by easonxy** [teubert/impact-estimator#27]
I am just uploading the GPS parts

**Comment by easonxy** [comment]
Let me check,  I will give you GPS on service tomorrow.

 

 

 

发件人: Christopher Teubert <notifications@github.com> 
发送时间: 2018年3月7日 18:02
收件人: teubert/impact-estimator <impact-estimator@noreply.github.com>
抄送: Eason <xuanyi2016@gmail.com>; Author <author@noreply.github.com>
主题: Re: [teubert/impact-estimator] GPS module (#27)

 

I noticed that you didn't implement your GPS app as part of the service, instead it is a locationmanager- that will be destroyed and created whenever the activity is changed, and will not be active if you close the app.

I was wondering, what was your reason for choosing this design?

Chris

**Comment by teubert** [comment]
Great, thank you!

Here's a good example that I found:
https://stackoverflow.com/questions/28535703/best-way-to-get-user-gps-location-in-background-in-android
