### ISSUE TITLE
Landscape mode?

### ISSUE THREAD

**Issue by teubert** [teubert/impact-estimator#34]

**Comment by xuangreradyi** [comment]
I am working on speed detection which decide the transport. 

Distance calculation for each mode.

The data will be reset to zero daily.

 

 

发件人: Christopher Teubert <notifications@github.com> 
发送时间: 2018年3月8日 18:46
收件人: teubert/impact-estimator <impact-estimator@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [teubert/impact-estimator] Landscape mode? (#34)
